# Generated by Django 3.2.6 on 2021-08-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_item_itemmm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Itemmm',
            new_name='Item',
        ),
    ]
